name: promenade
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  cupertino_icons: ^1.0.2
  yandex_mapkit:
    git:
      url: https://github.com/IvanKonon0v/yandex_mapkit.git
  permission_handler: ^11.0.1
  internet_connection_checker: ^1.0.0+1
  go_router: ^11.1.4
  intl: ^0.18.1
  http: ^1.1.0
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: VTB
      fonts:
        - asset: assets/fonts/VTBGroupUI-Regular.ttf
          weight: 400
        - asset: assets/fonts/VTBGroupUI-Medium.ttf
          weight: 500

flutter_intl:
  enabled: true